#!/bin/bash

#test file
#some lines

echo "hello world!"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
echo "hello world"
